input_data_path: "data/heart.csv"
input_data_for_validation: "data/sample_for_predict.csv"
output_model_path: "models/random_forest.pkl"
output_data_preprocessor_path: "models/data_preprocessor_rf.pkl"
predicts_path: "data/predicts.csv"
logger_config: "configs/logger_config.yml"
model_type: "Random Forest Classifier"
split_params:
  validation_size: 0.2
  random_state: 2021
feature_params:
  categorical_features: ['sex', 'cp', 'restecg', 'exang', 'slope', 'ca', 'fbs']
  numerical_features: ['chol', 'thalach', 'oldpeak', 'trestbps', 'age']
  target: 'target'
classifier_params:
  n_estimators: 100
  max_depth: 30
  random_state: 2021